primary_region = 'iad'

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
